// APP
export const MESSAGE_APP_LOADING_STARTED = 'MESSAGE_APP_LOADING_STARTED';
export type MESSAGE_APP_LOADING_STARTED = 'MESSAGE_APP_LOADING_STARTED';

export const MESSAGE_APP_LOADING_FINISHED = 'MESSAGE_APP_LOADING_FINISHED';
export type MESSAGE_APP_LOADING_FINISHED = 'MESSAGE_APP_LOADING_FINISHED';

// CHANNELS
export const MESSAGE_APP_CHANNEL_CHANGE_STARTED = 'MESSAGE_APP_CHANNEL_CHANGE_STARTED';
export type MESSAGE_APP_CHANNEL_CHANGE_STARTED = 'MESSAGE_APP_CHANNEL_CHANGE_STARTED';

export const MESSAGE_APP_CHANNEL_CHANGE_FINISHED = 'MESSAGE_APP_CHANNEL_CHANGE_FINISHED';
export type MESSAGE_APP_CHANNEL_CHANGE_FINISHED = 'MESSAGE_APP_CHANNEL_CHANGE_FINISHED';

export type MESSAGE_APP_CHANNELS_ACTIONS = MESSAGE_APP_CHANNEL_CHANGE_STARTED |
    MESSAGE_APP_CHANNEL_CHANGE_FINISHED | MESSAGE_APP_LOADING_FINISHED;

// MESSAGES
export type MESSAGE_APP_MESSAGES_ACTIONS = MESSAGE_APP_LOADING_FINISHED;

// USERS
export const MESSAGE_APP_USER_LOGGED_IN = 'MESSAGE_APP_USER_LOGGED_IN';
export type MESSAGE_APP_USER_LOGGED_IN = 'MESSAGE_APP_USER_LOGGED_IN';

export const MESSAGE_APP_USER_LOGGING_FAILED = 'MESSAGE_APP_USER_LOGGING_FAILED';
export type MESSAGE_APP_USER_LOGGING_FAILED = 'MESSAGE_APP_USER_LOGGING_FAILED';

export type MESSAGE_APP_LOGGING_ACTIONS =  MESSAGE_APP_USER_LOGGED_IN |
    MESSAGE_APP_USER_LOGGING_FAILED;

export type MESSAGE_APP_USERS_ACTIONS = MESSAGE_APP_LOGGING_ACTIONS | MESSAGE_APP_LOADING_FINISHED;
