export const MESSAGE_APP_CHANNEL_SELECTED = 'MESSAGE_APP_CHANNEL_SELECTED';
export const MESSAGE_APP_MESSAGE_SUBMITTED = 'MESSAGE_APP_MESSAGE_SUBMITTED';
export const MESSAGE_APP_DATA_LOADED = 'MESSAGE_APP_DATA_LOADED';
export const MESSAGE_APP_PROFILE_UPDATED = 'MESSAGE_APP_PROFILE_UPDATED';


